### ISSUE TITLE
Use standard project directory layout

### ISSUE THREAD

**Issue by rzhilkibaev** [Covata/delta-sdk-python#4]
Since this project is public we should stick to accepted conventions.
http://docs.python-guide.org/en/latest/writing/structure/

**Comment by myuwono** [comment]
80% agree on the ideas but I'm personally not a fan putting the main module outside of the `src` folder. In my experience packaging and tests can become a nightmare as now the `PYTHON_PATH` is the project root, which contains everything, including the packaged distributions as well (i.e. target folder etc).. check this blog out https://blog.ionelmc.ro/2014/06/25/python-packaging-pitfalls/
