### ISSUE TITLE
Refactor logging implementation

### ISSUE THREAD

**Issue by numbat** [Covata/delta-sdk-python#50]
Do we need the logging at all?

**Comment by rzhilkibaev** [comment]
Did you want to say 'Do users need the logging at all?'? :)

**Comment by myuwono** [comment]
There's this awesome blog post that captures my mixed feeling about logging from within library code. I vote for either minimal or nothing at all:

http://pythonsweetness.tumblr.com/post/67394619015/use-of-logging-package-from-within-a-library

**Comment by myuwono** [comment]
I'm removing `LogMixin` and `caller()` for now - until we finally need it.
