### ISSUE TITLE
Fix code style issues

### ISSUE THREAD

**Issue by myuwono** [Covata/delta-sdk-python#79]
I raised this issue when I was setting up Codacy - it was incorrectly flagging code duplications in ApiClient which went away after proper setup.

But there is one legit code style flag around `id`: 

Identity, Secret, (and Event) classes overloads `id`. `id` is a reserved function in python to get the pointer to an object in memory. Where it gets confusing is that there's an `id` property attached to the identity/secret/event object; whereas we know for a fact that `id(identity) != identity.id`. An approach libraries like numpy or pandas use is to postfix the offending variable with an underscore, e.g. `id_` instead of `id` which I'm aware would also attract some confusion around it. Another (possibly more sound) proposition is to explicitly declare the id, e.g. `identity_id`, `secret_id` or `event_id`

**Comment by numbat** [comment]
@myuwono - can you elaborate on which code style issues need to be fixed?

**Comment by myuwono** [comment]
thanks! elaborated 👍 It's more of a python-related thingy so feel free to close this if you reckon it's a no-issue

**Comment by numbat** [comment]
Thanks for that! 

I think the second approach of prefixing the id with the type is going to be more maintainable and readable in the long run.
